apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucaslaredo-playlist-recommender-deployment
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
      lucaslaredo-playlist-recommender-model=laredoo/playlists-recommender-system-model
      lucaslaredo-playlist-recommender-api=laredoo/playlists-recommender-system-api
    argocd-image-updater.argoproj.io/lucaslaredo-playlist-recommender-model.update-strategy: semver
    argocd-image-updater.argoproj.io/lucaslaredo-playlist-recommender-api.update-strategy: semver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lucaslaredo-playlist-recommender
  template:
    metadata:
      labels:
        app: lucaslaredo-playlist-recommender
    spec:
      initContainers:
      - name: lucaslaredo-playlist-recommender-model
        image: laredoo/playlists-recommender-system-model:latest
        volumeMounts:
        - name: data-volume
          mountPath: /shared/data
        env:
        - name: PLAYLIST_PATH
          value: "/shared/data/2023_spotify_ds1.csv"
        - name: EXPORT_PATH
          value: "/shared/data/rules.pkl"
      containers:
      - name: lucaslaredo-playlist-recommender-api
        image: laredoo/playlists-recommender-system-api:latest
        ports:
        - containerPort: 52045
        volumeMounts:  
        - name: data-volume
          mountPath: /shared/data
        env:
        - name: RULES_PATH
          value: "/shared/data/rules.pkl"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: project2-pv2-lucaslaredo