apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucaslaredo-playlist-recommender-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lucaslaredo-playlist-recommender
  template:
    metadata:
      labels:
        app: lucaslaredo-playlist-recommender
    spec:
      initContainers:
      - name: lucaslaredo-playlist-recommender-model
        image: laredoo/playlists-recommender-system-model
        volumeMounts:
        - name: data-volume
          mountPath: /shared/data
        env:
        - name: PLAYLIST_PATH
          valueFrom:
            configMapKeyRef:
              name: playlist-dataset-config
              key: PLAYLIST_PATH
        - name: EXPORT_PATH
          value: "/shared/data/rules.pkl"
      containers:
      - name: lucaslaredo-playlist-recommender-api
        image: laredoo/playlists-recommender-system-api
        ports:
        - containerPort: 52045
        volumeMounts:  
        - name: data-volume
          mountPath: /shared/data
        env:
        - name: RULES_PATH
          value: "/shared/data/rules.pkl"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: project2-pv2-lucaslaredo