apiVersion: apps/v1
kind: Deployment
metadata:
  name: 2023_spotify_ds1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lucaslaredo-playlist-recommender
  template:
    metadata:
      labels:
        app: lucaslaredo-playlist-recommender
    spec:
      containers:
      - env:
        - name: RULES_PATH
          value: /shared/data/rules.pkl
        image: laredoo/playlists-recommender-system-api
        name: lucaslaredo-playlist-recommender-api
        ports:
        - containerPort: 52045
        volumeMounts:
        - mountPath: /shared/data
          name: data-volume
      initContainers:
      - env:
        - name: PLAYLIST_PATH
          valueFrom:
            configMapKeyRef:
              key: PLAYLIST_PATH
              name: playlist-dataset-config
        - name: EXPORT_PATH
          value: /shared/data/rules.pkl
        image: laredoo/playlists-recommender-system-model
        name: lucaslaredo-playlist-recommender-model
        volumeMounts:
        - mountPath: /shared/data
          name: data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: project2-pv2-lucaslaredo
