apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucaslaredo-playlist-recommender-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lucaslaredo-playlist-recommender
  template:
    metadata:
      labels:
        app: lucaslaredo-playlist-recommender
    spec:
      initContainers:
      - name: lucaslaredo-playlist-recommender-model
        image: laredoo/playlists-recommender-system-model:0.1
        volumeMounts:
        - name: data-volume
          mountPath: /model/data
        env:
        - name: PLAYLIST_PATH
          value: "./model/data/2023_spotify_ds1.csv"
        - name: EXPORT_PATH
          value: "./app/data/rules.pkl"
      containers:
      - name: lucaslaredo-playlist-recommender-api
        image: laredoo/playlists-recommender-system-api
        ports:
        - containerPort: 52045
        volumeMounts:  
        - name: data-volume
          mountPath: /app/data
        env:
        - name: RULES_PATH
          value: "./app/data/rules.pkl"
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: project2-pv2-lucaslaredo  