apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-lucaslaredo
  namespace: lucaslaredo
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 700Mi
  storageClassName: default-storage-class-lucaslaredo
