apiVersion: v1
kind: Service
metadata:
  name: lucaslaredo-playlist-recommender-service
  labels:
    app: lucaslaredo-playlist-recommender
spec:
  selector:
    app: lucaslaredo-playlist-recommender
  ports:
    - protocol: TCP
      port: 52045                  
      targetPort: 52045         
  type: ClusterIP              