apiVersion: v1
kind: Service
metadata:
  name: lucaslaredo-playlist-recommender-service
  namespace: lucaslaredo
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 52045                  
      targetPort: 52045         
  selector:
    app: lucaslaredo-playlist-recommender